services:
  weather-app:
    build:
      context: .
    container_name: weather-app-service
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/var/www/html/.env
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: weather-app-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: weatherdatabase
    ports:
      - "23567:27017"
    volumes:
      - weather-app-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: weather-app-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weatherdatabase
    ports:
      - "5555:5432"
    volumes:
      - weather-app-postgresql:/data/db/postgresql

volumes:
  weather-app-mongodb:
    driver: local
  weather-app-postgresql:
    driver: local
